version: "3.7"
services:
  chat-app:
    image: llmate-chat-app
    container_name: llmate-chat-app
    build:
      context: .
    env_file: .env
    restart: always
    networks:
      - agent_pub
    ports:
      - "3000:3000"



networks:
  default:
    driver: bridge
  
  agent_pub:
    internal: false
  agent_net:
    internal: true