// Sample data for the BasicTable
export const sampleData = [
    { id: 1, fieldName: 'Temperature', value: ['23°C', '24°C'] },
    { id: 2, fieldName: 'Pressure', value: ['1 atm', '1.05 atm'] },
    { id: 3, fieldName: 'Humidity', value: '45%' },
    { id: 4, fieldName: 'Wind Speed', value: ['12 km/h', '15 km/h', '14 km/h', '16 km/h', '17 km/h'] },
    { id: 5, fieldName: 'Visibility', value: ['10 km', '12 km'] },
    { id: 6, fieldName: 'Dew Point', value: ['16°C', '17°C'] },
    { id: 7, fieldName: 'UV Index', value: ['5', '6'] },
    { id: 8, fieldName: 'Air Quality', value: ['Good', 'Moderate', 'Bad', 'Poor', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'] },
    { id: 9, fieldName: 'Sunrise', value: '6:15 AM' },
    { id: 10, fieldName: 'Sunset', value: '7:45 PM' },
    { id: 11, fieldName: 'Cloud Cover', value: '20%' },
    { id: 12, fieldName: 'Precipitation', value: '0 mm' },
    { id: 13, fieldName: 'Snowfall', value: '0 cm' },
    { id: 14, fieldName: 'Heat Index', value: '25°C' },
    { id: 15, fieldName: 'Wind Chill', value: '21°C' },
    { id: 16, fieldName: 'Sea Level Pressure', value: '1013 hPa' },
    { id: 17, fieldName: 'Ground Temperature', value: '19°C' },
    { id: 18, fieldName: 'Air Density', value: '1.225 kg/m³' },
    { id: 19, fieldName: 'Ozone Level', value: '300 DU' },
    { id: 20, fieldName: 'Visibility Range', value: '9 km' },
    { id: 21, fieldName: 'Pollen Count', value: 'Low' },
    { id: 22, fieldName: 'Soil Moisture', value: '35%' },
    { id: 23, fieldName: 'Leaf Wetness', value: 'Wet' },
    { id: 24, fieldName: 'Chlorophyll Content', value: 'High' },
    { id: 25, fieldName: 'Soil pH', value: '6.5' },
    { id: 26, fieldName: 'Evapotranspiration', value: '4 mm' },
    { id: 27, fieldName: 'Lightning Strikes', value: '0' },
    { id: 28, fieldName: 'Solar Radiation', value: '800 W/m²' },
    { id: 29, fieldName: 'Moon Phase', value: 'Waxing Crescent' },
    { id: 30, fieldName: 'Barometric Trend', value: 'Rising' },
    { id: 31, fieldName: 'Air Quality Index', value: '45' },
    { id: 32, fieldName: 'CO2 Levels', value: '400 ppm' },
    { id: 33, fieldName: 'Methane Levels', value: '1.8 ppm' },
    { id: 34, fieldName: 'Nitrogen Dioxide', value: '0.02 ppm' },
    { id: 35, fieldName: 'Sulfur Dioxide', value: '0.005 ppm' },
    { id: 36, fieldName: 'Particulate Matter', value: '12 µg/m³' },
    { id: 37, fieldName: 'VOC Levels', value: '0.5 ppm' },
    { id: 38, fieldName: 'Albedo', value: '0.3' },
    { id: 39, fieldName: 'Surface Roughness', value: 'Medium' },
    { id: 40, fieldName: 'Frontal Boundary', value: 'Cold Front' },
    { id: 41, fieldName: 'Isotherm', value: '30°C' },
    { id: 42, fieldName: 'Isobar', value: '1000 hPa' },
    { id: 43, fieldName: 'Weather Station ID', value: 'WX123' },
    { id: 44, fieldName: 'Geolocation', value: '51.5074° N, 0.1278° W' },
    { id: 45, fieldName: 'Satellite ID', value: 'SAT987' },
    { id: 46, fieldName: 'Model Run', value: 'GFS 12Z' },
    { id: 47, fieldName: 'Forecast Hour', value: '36 hr' },
    { id: 48, fieldName: 'Forecast Probability', value: '80%' },
    { id: 49, fieldName: 'Event Probability', value: '70%' },
    { id: 50, fieldName: 'Return Interval', value: '10 years' },
    { id: 51, fieldName: 'Climatic Zone', value: 'Temperate' },
    { id: 52, fieldName: 'Season', value: 'Summer' },
    { id: 53, fieldName: 'Synoptic Pattern', value: 'High Pressure' }
];